### PR TITLE
Turn off Debug mode, allow remote access and add dockerfile

### PR DESCRIPTION
**Pull request by Merlyn42**

### CODE REVIEW

**Comment by Daxiongmao87** [comment]
Hey @Merlyn42 thank you for the contribution.  I assume this has been tested? :) Specifically the Dockerfile? Thanks for catching the debug

**Comment by Daxiongmao87** [comment]
Also could you add to the README.md a docker-compose and/or docker run example command to use the Dockerfile?

**Comment by Merlyn42** [comment]
@Daxiongmao87 Well it worked for me 😄 . I've added the instructions

**Comment by Daxiongmao87** [comment]
ill review and possibly merge tonight!

**Review by Daxiongmao87 — APPROVED** [review]

**Pull request merged**
